function uiclass()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load uiclass                           

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','global p1 p2;X=[];Y=[];ker=''linear'';C=Inf;p1=1;p2=0;sep=1;centrefig', ...
	'MenuBar','none', ...
	'Name','Support Vector Classification', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[176 132 800 580], ...
	'Resize','off', ...
	'Tag','Fig1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback',mat2, ...
	'CreateFcn',mat3, ...
	'Position',[13.5 409.5 126.75 15], ...
	'String',mat4, ...
	'Style','popupmenu', ...
	'Tag','svmMenu', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat5, ...
	'Position',[514.5 342.75 68.25 23.25], ...
	'String','Load', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat6, ...
	'Position',[514.5 308.25 68.25 23.25], ...
	'String','Save', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat7, ...
	'ForegroundColor',[0 0 1], ...
	'Position',[514.5 261.75 68.25 23.25], ...
	'String','Class A', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat8, ...
	'ForegroundColor',[1 0 0], ...
	'Position',[514.5 225 68.25 23.25], ...
	'String','Class B', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat9, ...
	'Position',[514.5 189 68.25 23.25], ...
	'String','Clear Data', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat10, ...
	'Position',[514.5 115.5 68.25 23.25], ...
	'String','Classify', ...
	'Tag','Pushbutton1');
b = axes('Parent',a, ...
	'Units','points', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[0 0 0], ...
	'ColorOrder',mat11, ...
	'Position',[0 27 496 372], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'XLimMode','manual', ...
	'XTickLabelMode','manual', ...
	'YColor',[0 0 0], ...
	'YLimMode','manual', ...
	'YTickLabelMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498485 -0.0222222 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0166667 0.49697 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.00151515 1.09495 0], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498485 1.01414 0], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',mat12, ...
	'CreateFcn',mat13, ...
	'Position',[245.25 408.75 76.5 15.75], ...
	'String','Separable', ...
	'Style','checkbox', ...
	'Tag','svmCheckSep', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','C = str2num(get(findobj(gcf,''Tag'',''svmEditBound''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditBound''),''String'',num2str(C));', ...
	'Position',[386 409.5 46.5 14.25], ...
	'String','Inf', ...
	'Style','edit', ...
	'Tag','svmEditBound', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','p1 = str2num(get(findobj(gcf,''Tag'',''svmEditP1''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svmEditP1''),''String'',num2str(p1));', ...
	'Position',[192.75 409.5 23.25 14.25], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','svmEditP1', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[147.75 410.25 39.75 12.75], ...
	'Style','text', ...
	'Tag','svmTextP1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[338.75 411 40.5 12], ...
	'String','Bound', ...
	'Style','text', ...
	'Tag','svmTextBound', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[24 6 428.25 14.25], ...
	'Style','text', ...
	'Tag','svmTextStatus');
