function uiregress()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load uiregress                         

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','global p1 p2;X=[];Y=[];ker=''linear'';e=0.0;C=Inf;p1=1;p2=0;sep=1;centrefig', ...
	'MenuBar','none', ...
	'Name','Support Vector Regression', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[176 132 800 580], ...
	'Resize','off', ...
	'Tag','Fig1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback',mat2, ...
	'CreateFcn',mat3, ...
	'Position',[13.5 409.5 126.75 15], ...
	'String',mat4, ...
	'Style','popupmenu', ...
	'Tag','svrMenu', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat5, ...
	'Position',[514.5 342.75 68.25 23.25], ...
	'String','Load', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat6, ...
	'Position',[514.5 308.25 68.25 23.25], ...
	'String','Save', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat7, ...
	'ForegroundColor',[1 0 0], ...
	'Position',[514.5 225 68.25 23.25], ...
	'String','Data', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat8, ...
	'Position',[514.5 189 68.25 23.25], ...
	'String','Clear Data', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback',mat9, ...
	'Position',[514.5 115.5 68.25 23.25], ...
	'String','Regress', ...
	'Tag','Pushbutton1');
b = axes('Parent',a, ...
	'Units','points', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'CLim',[-5.23805 5.23805], ...
	'CLimMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat10, ...
	'DrawMode','fast', ...
	'Position',[0.75 27 495.75 372], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'XLim',[-1.50393 2.3052], ...
	'XLimMode','manual', ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[-0.520322 1.9238], ...
	'YLimMode','manual', ...
	'YTickLabelMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.394864 1.95836 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.394864 -0.559823 0], ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-1.54433 0.694333 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-1.51547 2.15587 0], ...
	'Tag','Axes1Text1', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','C = str2num(get(findobj(gcf,''Tag'',''svrEditBound''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svrEditBound''),''String'',num2str(C))', ...
	'Position',[316 409.5 46.5 14.25], ...
	'String','Inf', ...
	'Style','edit', ...
	'Tag','svrEditBound');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','p1 = str2num(get(findobj(gcf,''Tag'',''svrEditP1''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svrEditP1''),''String'',num2str(p1))', ...
	'Position',[190.75 409.5 23.25 14.25], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','svrEditP1', ...
	'Visible','off');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[147.75 410.25 39 12.75], ...
	'Style','text', ...
	'Tag','svrTextP1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[258.75 410.25 40.5 12], ...
	'String','Bound', ...
	'Style','text', ...
	'Tag','svrTextBound');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[24 6 428.25 14.25], ...
	'Style','text', ...
	'Tag','svrTextStatus');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[368.25 410.25 60.75 12], ...
	'String','e insensitivity', ...
	'Style','text', ...
	'Tag','svrTexte');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','e = str2num(get(findobj(gcf,''Tag'',''svrEdite''),''String''));', ...
	'CreateFcn','set(findobj(gcf,''Tag'',''svrEdite''),''String'',num2str(e))', ...
	'Position',[432 409.5 46.5 14.25], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','svrEdite');
